/* =========================================================
   FDE Academy · 课程体系（2026）
   ---------------------------------------------------------
   字段说明（改内容只需动这个文件）：
     b  = buildings 学部/教学楼：{ id, icon, name, sub, color, desc, courses }
     c  = credits 学分   h = hours 学时   lv = 难度 1-5
     core = 核心课（毕业必过）  g = 学习目标  cp = 验收标准
     r  = 推荐资源 [ [名称, 链接或 null] ]
   ========================================================= */
const DATA = {
  /* ============================ 中文 ============================ */
  zh: {
    buildings: [
      {
        id: "found", icon: "🏛️", name: "基础学部", sub: "Foundations", color: "#4fe3c1",
        desc: "所有现场问题的终点都是这些基本功。别跳课，它们会在最尴尬的时刻回来找你。",
        courses: [
          { id: "f1", n: "Linux 与命令行生存", c: 3, h: 20, lv: 2, core: true,
            g: ["文件系统、权限、进程、服务的排查套路", "ssh / 端口 / 日志定位三板斧", "用 shell 脚本把重复劳动自动化"],
            cp: "能在陌生服务器上 10 分钟内定位「服务起不来」的原因并给出结论",
            r: [["The Linux Command Line（书）", null], ["Debian/Ubuntu 官方管理员手册", "https://www.debian.org/doc/manuals/debian-handbook/"]] },
          { id: "f2", n: "Git 与协作工程", c: 3, h: 16, lv: 2, core: true,
            g: ["分支策略、rebase 与冲突处理", "PR / Code Review 礼仪", "多版本并行发布时的分支管理"],
            cp: "能在多人并行开发的仓库里干净地回滚一次线上事故提交",
            r: [["Pro Git 中文版", "https://git-scm.com/book/zh/v2"]] },
          { id: "f3", n: "网络与 API 基础", c: 3, h: 18, lv: 3, core: true,
            g: ["HTTP / DNS / TLS / 代理与内网穿透", "REST 与 WebSocket 的取舍", "抓包排查（curl / 浏览器 DevTools）"],
            cp: "能独立判断「接口不通」是 DNS、证书、代理还是业务代码的问题",
            r: [["MDN HTTP 文档", "https://developer.mozilla.org/zh-CN/docs/Web/HTTP"]] },
          { id: "f4", n: "Python 工程化", c: 4, h: 30, lv: 3, core: true,
            g: ["虚拟环境与依赖锁定（uv / poetry）", "类型标注、日志、配置管理", "异步与并发的基本取舍"],
            cp: "交付一个可被别人 pip install 并直接跑起来的小工具，含 README 与测试",
            r: [["Python 官方教程", "https://docs.python.org/zh-cn/3/tutorial/"]] },
          { id: "f5", n: "SQL 与数据建模", c: 3, h: 20, lv: 3, core: false,
            g: ["查询优化与索引直觉", "宽表 / 星型模型 / 缓慢变化维", "把业务口径翻译成 SQL"],
            cp: "面对一张陌生业务库，能画出核心实体关系并写出正确的统计口径",
            r: [["PostgreSQL 官方教程", "https://www.postgresql.org/docs/current/tutorial.html"]] },
        ],
      },
      {
        id: "craft", icon: "🧱", name: "软件工程学部", sub: "Software Craft", color: "#7c8cff",
        desc: "FDE 写的代码常常要活过自己的任期。写得快是本事，写得能交接才是职业。",
        courses: [
          { id: "s1", n: "后端服务开发", c: 4, h: 36, lv: 3, core: true,
            g: ["API 设计、鉴权、分页与幂等", "任务队列与后台作业", "配置、密钥与环境隔离"],
            cp: "独立写出一个带鉴权、可观测、有测试的 REST 服务并部署上线",
            r: [["FastAPI 官方文档", "https://fastapi.tiangolo.com/"]] },
          { id: "s2", n: "前端与可视化", c: 3, h: 28, lv: 3, core: false,
            g: ["能做出能用的界面（不必是设计师）", "图表与看板：让数据说服客户", "表单、加载态、错误处理"],
            cp: "用最少的前端代码做出一个客户愿意每天打开的看板",
            r: [["MDN Web 开发入门", "https://developer.mozilla.org/zh-CN/docs/Learn"]] },
          { id: "s3", n: "系统设计入门", c: 4, h: 30, lv: 4, core: true,
            g: ["容量估算、缓存、队列、限流", "单体 vs 拆分的决策依据", "为「不可用的依赖」设计降级"],
            cp: "给一个真实业务场景画出架构图，并说清每个组件的失败代价",
            r: [["12 Factor App", "https://12factor.net/zh_cn/"]] },
          { id: "s4", n: "测试与质量保障", c: 3, h: 20, lv: 3, core: false,
            g: ["单测 / 集成 / 端到端的分层", "造数据：fixtures 与契约测试", "改别人的代码前先补一张网"],
            cp: "给一个没有测试的老模块补上关键路径测试，覆盖率与信心一起上升",
            r: [["pytest 官方文档", "https://docs.pytest.org/"]] },
          { id: "s5", n: "CI/CD 与流水线", c: 3, h: 18, lv: 3, core: true,
            g: ["构建、测试、镜像、发布一条龙", "环境分层与灰度回滚", "把「人肉操作」全部脚本化"],
            cp: "从零搭一条流水线：推代码 → 测试 → 镜像 → 部署 → 失败自动回滚",
            r: [["GitHub Actions 文档", "https://docs.github.com/actions"]] },
        ],
      },
      {
        id: "ai", icon: "🧠", name: "数据与 AI 学部", sub: "Data & AI", color: "#ff8fb1",
        desc: "2026 年的 FDE 不会做 AI，就像 2016 年不会写 SQL。重点是工程化，不是炼丹。",
        courses: [
          { id: "a1", n: "数据管道与 ETL", c: 3, h: 26, lv: 3, core: true,
            g: ["批式与流式的基本分野", "脏数据、对账与补数机制", "从客户系统（Excel / SAP / API）取数"],
            cp: "把客户三份格式不一的数据接成一张可信的表，并给出对账报告",
            r: [["Apache Airflow 文档", "https://airflow.apache.org/docs/"]] },
          { id: "a2", n: "RAG 与向量检索", c: 4, h: 30, lv: 4, core: true,
            g: ["切分、嵌入、召回、重排", "向量库选型与混合检索", "引用溯源与幻觉抑制"],
            cp: "搭一个能答对的文档助手，并能量化「答对率」而不是靠感觉",
            r: [["Qdrant 文档", "https://qdrant.tech/documentation/"]] },
          { id: "a3", n: "LLM 应用工程", c: 4, h: 30, lv: 3, core: true,
            g: ["结构化输出、函数调用与重试", "流式体验与超时处理", "模型选型：效果 / 成本 / 合规三角"],
            cp: "上线一个有护栏、有日志、有降级方案的 LLM 功能",
            r: [["OpenAI 开发文档", "https://platform.openai.com/docs"], ["Anthropic 开发文档", "https://docs.anthropic.com/"]] },
          { id: "a4", n: "Agent 与工具调用", c: 4, h: 32, lv: 5, core: false,
            g: ["什么时候不该用 Agent", "工具设计、状态与上下文压缩", "人类兜底与审批环节"],
            cp: "做一个带人工确认环节的流程自动化，并证明它比脚本更值得",
            r: [["12 Factor Agents（方法论）", null]] },
          { id: "a5", n: "评测、成本与提示工程", c: 3, h: 20, lv: 3, core: true,
            g: ["建评测集：从 20 条真实样例开始", "Token / 延迟 / 缓存的成本账", "提示的版本管理与回归测试"],
            cp: "为你的 AI 功能建一套可复跑的评测，并给出成本下降方案",
            r: [["OpenAI 评测指南", "https://platform.openai.com/docs/guides/evals"]] },
        ],
      },
      {
        id: "infra", icon: "🛠️", name: "部署与基础设施学部", sub: "Deployment & Infra", color: "#ffd166",
        desc: "客户现场没有「我的机器上能跑」。这里训练的就是跨环境交付能力。",
        courses: [
          { id: "i1", n: "Docker 与镜像工程", c: 3, h: 20, lv: 2, core: true,
            g: ["分层、缓存、瘦身与安全扫描", "多架构镜像（x86 / ARM）", "本地复现生产环境"],
            cp: "把一个祖传项目容器化，镜像体积与启动时间都给出前后对比",
            r: [["Docker 入门", "https://docs.docker.com/get-started/"]] },
          { id: "i2", n: "Kubernetes 基础", c: 4, h: 32, lv: 4, core: true,
            g: ["Pod / Service / Ingress / ConfigMap", "资源限制、探针与滚动更新", "会用 kubectl 排查，而不是只会 apply"],
            cp: "把一个三件套服务部署到集群，并完成一次无损滚动更新",
            r: [["Kubernetes 官方教程", "https://kubernetes.io/docs/tutorials/"]] },
          { id: "i3", n: "云与基础设施即代码", c: 4, h: 30, lv: 4, core: true,
            g: ["Terraform 管理资源生命周期", "多云差异与锁定风险", "环境与密钥的分层管理"],
            cp: "用代码创建一整套环境，并能在另一个账号/区域一键复现",
            r: [["Terraform 文档", "https://developer.hashicorp.com/terraform/docs"]] },
          { id: "i4", n: "可观测性三件套", c: 3, h: 22, lv: 3, core: true,
            g: ["日志、指标、链路的分工", "SLO / 告警设计（别吵醒人）", "上线后如何证明「它真的更好了」"],
            cp: "为服务配好指标与告警，并做一次真实的故障复盘",
            r: [["OpenTelemetry 文档", "https://opentelemetry.io/docs/"]] },
          { id: "i5", n: "离线、边缘与私有化部署", c: 4, h: 28, lv: 5, core: true,
            g: ["内网 / 无外网 / 国产化环境交付", "离线安装包与依赖镜像打包", "数据不出域的架构约束"],
            cp: "在无外网环境完成一次完整部署，并写出可复制的交付手册",
            r: [["Kubernetes 离线部署实践（搜索关键词）", null]] },
        ],
      },
      {
        id: "fde", icon: "🎯", name: "前沿部署学部", sub: "Forward Deployed Skills", color: "#ff6b81",
        desc: "本学院的立校之本。技术决定你能不能被录用，这些决定你能不能被留下。",
        courses: [
          { id: "d1", n: "需求挖掘与问题定义", c: 4, h: 24, lv: 4, core: true,
            g: ["把「我们要个 AI」翻译成可验收的问题", "现场观察：跟一天真实工作流", "区分真需求、伪需求与政治需求"],
            cp: "输出一页纸问题定义：现状、痛点、量化目标、验收口径，客户签字确认",
            r: [["The Mom Test（书）", null]] },
          { id: "d2", n: "快速原型：72 小时 POC", c: 4, h: 30, lv: 4, core: true,
            g: ["用假数据先跑通体验", "砍需求：只做打动人的那 20%", "可抛弃代码的勇气"],
            cp: "72 小时内交付一个能演示的原型，并明确写出「不做什么」",
            r: [["POC 到生产的鸿沟（搜索关键词）", null]] },
          { id: "d3", n: "演示与讲故事", c: 3, h: 18, lv: 3, core: true,
            g: ["用客户的语言讲，不用技术名词", "一次演示只打一个记忆点", "现场翻车的预案与救场"],
            cp: "做一次 10 分钟演示，会后客户能自己复述出价值主张",
            r: [["Made to Stick（书）", null]] },
          { id: "d4", n: "期望管理与跨组织协作", c: 3, h: 20, lv: 4, core: true,
            g: ["周报、风险清单与坏消息提前说", "搞定甲方的 IT、业务与安全三方", "拒绝的艺术：说不且不掉单"],
            cp: "连续 8 周输出风险可控的项目周报，无一次预期外升级",
            r: [["Crucial Conversations（书）", null]] },
          { id: "d5", n: "交付、文档与知识转移", c: 3, h: 20, lv: 3, core: true,
            g: ["交付物清单与验收文档", "让客户会用的文档才是好文档", "培训与交接：你走了系统还在"],
            cp: "完成一次交付：文档、培训录像、运维手册、交接会，客户能独立运行两周",
            r: [["Write the Docs 指南", "https://www.writethedocs.org/guide/"]] },
          { id: "d6", n: "从 POC 到产品化", c: 4, h: 28, lv: 5, core: true,
            g: ["识别可复用部分，二次交付降本", "把一次项目沉淀成标准件", "判断何时该说「这个不值得再做」"],
            cp: "把做过的一个项目抽象成可复用方案，第二次交付时间下降 50%",
            r: [["《启示录》/ Inspired（书）", null]] },
        ],
      },
      {
        id: "cap", icon: "🏆", name: "实战馆", sub: "Capstone Projects", color: "#9d7cff",
        desc: "毕业前必须真刀真枪交付。每个项目都要有可展示的成果物和可讲的复盘。",
        courses: [
          { id: "p1", n: "项目一：客户数据接入与看板", c: 5, h: 40, lv: 3, core: true,
            g: ["对接真实脏数据并治理", "做一个客户愿意每天开的看板", "给出口径说明与对账"],
            cp: "交付看板 + 数据字典 + 一份「数据可信度」说明",
            r: [["Metabase 文档", "https://www.metabase.com/docs/latest/"]] },
          { id: "p2", n: "项目二：离线私有化部署演练", c: 5, h: 45, lv: 5, core: true,
            g: ["断网环境完整部署", "依赖与镜像的离线打包", "交付手册与回滚方案"],
            cp: "在模拟内网环境完成部署，写出可复制的交付手册",
            r: [["Kubernetes 官方文档", "https://kubernetes.io/docs/home/"]] },
          { id: "p3", n: "项目三：RAG 知识助手上线", c: 5, h: 45, lv: 4, core: true,
            g: ["真实语料、真实评估集", "引用溯源与人工兜底", "成本与延迟优化"],
            cp: "上线助手并给出答对率、成本、用户反馈三项数据",
            r: [["Qdrant 文档", "https://qdrant.tech/documentation/"]] },
          { id: "p4", n: "项目四：流程自动化与 Agent", c: 5, h: 45, lv: 5, core: false,
            g: ["选一个高频人工流程", "设计人工确认与审计", "量化节省的人时"],
            cp: "自动化一条流程，并给出人时节省的度量与风险清单",
            r: [["Anthropic 工具调用文档", "https://docs.anthropic.com/"]] },
          { id: "p5", n: "毕业设计：完整交付一个客户项目", c: 6, h: 80, lv: 5, core: true,
            g: ["从需求到上线到交接全链路", "有复盘：踩坑、权衡、下次怎么做", "能在面试里讲 15 分钟"],
            cp: "完整交付 + 复盘文档 + 15 分钟讲述，即可申请毕业",
            r: [["Palantir 关于 FDE 的实践文章", "https://www.palantir.com/"]] },
        ],
      },
    ],

    semesters: [
      { no: "S1", title: "地基期（1–3 月）", goal: "把基本功补齐，能在服务器上独立排障。",
        items: ["Linux 与命令行生存", "Git 与协作工程", "网络与 API 基础", "Python 工程化", "SQL 与数据建模"],
        out: "交付物：一个容器化、带测试、有 CI 的小工具" },
      { no: "S2", title: "工程期（4–7 月）", goal: "能独立交付一个可运行、可观测、可回滚的服务。",
        items: ["后端服务开发", "系统设计入门", "Docker 与镜像工程", "CI/CD 与流水线", "可观测性三件套"],
        out: "交付物：一条从提交到上线的完整流水线 + 一个线上服务" },
      { no: "S3", title: "智能期（8–12 月）", goal: "把 AI 能力工程化地接进客户业务，而不是做 Demo。",
        items: ["数据管道与 ETL", "RAG 与向量检索", "LLM 应用工程", "评测、成本与提示工程", "Kubernetes 基础"],
        out: "交付物：一个可量化效果的 AI 功能（含评测集与成本账）" },
      { no: "S4", title: "前线期（13–18 月）", goal: "走进客户现场，把技术变成业务结果。",
        items: ["需求挖掘与问题定义", "72 小时 POC", "演示与讲故事", "期望管理与协作", "交付与知识转移", "毕业设计"],
        out: "交付物：一次完整客户交付 + 复盘文档 + 毕业证" },
    ],

    rules: [
      { t: "先去现场，再写代码", d: "在客户工位上坐一天，胜过读十页需求文档。真正的问题藏在他们习以为常的动作里。" },
      { t: "演示比完美重要", d: "周三拿出一个能点的东西，胜过月底交一份完美方案。反馈越早，返工越少。" },
      { t: "坏消息要早说", d: "延期、风险、做不到的功能——提前说是专业，临时说叫事故。" },
      { t: "代码要能交接", d: "你总会离开这个项目。README、脚本、文档，是给下一个人的救生圈。" },
      { t: "为失败设计", d: "依赖会挂、网络会断、模型会胡说。想清楚每个组件挂掉时用户看到什么。" },
      { t: "砍需求是核心技能", d: "打动决策者的往往只有 20% 的功能。找到它，把剩下的勇敢砍掉。" },
      { t: "交付才算完成", d: "跑通不等于交付。客户会用、愿意用、离了你能用，才算闭环。" },
    ],
  },

  /* ============================ English ============================ */
  en: {
    buildings: [
      {
        id: "found", icon: "🏛️", name: "Foundations", sub: " basics", color: "#4fe3c1",
        desc: "Every on-site fire eventually traces back to these. Skip them and they return at the worst possible moment.",
        courses: [
          { id: "f1", n: "Linux & Command Line Survival", c: 3, h: 20, lv: 2, core: true,
            g: ["Filesystem, permissions, processes, services", "ssh / ports / log triage", "Automate repetitive work with shell"],
            cp: "Diagnose \"the service won't start\" on an unfamiliar box within 10 minutes",
            r: [["The Linux Command Line (book)", null], ["Debian Administrator's Handbook", "https://www.debian.org/doc/manuals/debian-handbook/"]] },
          { id: "f2", n: "Git & Collaborative Engineering", c: 3, h: 16, lv: 2, core: true,
            g: ["Branching strategy, rebase, conflict resolution", "PR & code review etiquette", "Managing parallel releases"],
            cp: "Cleanly revert an incident-causing commit in a busy shared repo",
            r: [["Pro Git", "https://git-scm.com/book/en/v2"]] },
          { id: "f3", n: "Networking & API Basics", c: 3, h: 18, lv: 3, core: true,
            g: ["HTTP / DNS / TLS / proxies", "REST vs WebSockets", "Packet-level debugging (curl, DevTools)"],
            cp: "Tell apart DNS, certificate, proxy and application bugs without guessing",
            r: [["MDN HTTP", "https://developer.mozilla.org/en-US/docs/Web/HTTP"]] },
          { id: "f4", n: "Python for Production", c: 4, h: 30, lv: 3, core: true,
            g: ["Environments and dependency locking (uv / poetry)", "Typing, logging, configuration", "Async and concurrency trade-offs"],
            cp: "Ship a pip-installable tool with README and tests someone else can run",
            r: [["Python Tutorial", "https://docs.python.org/3/tutorial/"]] },
          { id: "f5", n: "SQL & Data Modeling", c: 3, h: 20, lv: 3, core: false,
            g: ["Query plans and index intuition", "Wide tables, star schemas, slow-changing dimensions", "Turning business definitions into SQL"],
            cp: "Map an unfamiliar database's core entities and write correct metrics",
            r: [["PostgreSQL Tutorial", "https://www.postgresql.org/docs/current/tutorial.html"]] },
        ],
      },
      {
        id: "craft", icon: "🧱", name: "Software Craft", sub: "engineering", color: "#7c8cff",
        desc: "FDE code usually outlives its author. Writing fast is skill; writing handover-able is professionalism.",
        courses: [
          { id: "s1", n: "Backend Services", c: 4, h: 36, lv: 3, core: true,
            g: ["API design, auth, pagination, idempotency", "Job queues and background work", "Config, secrets, environment isolation"],
            cp: "Ship an authenticated, observable, tested REST service",
            r: [["FastAPI Docs", "https://fastapi.tiangolo.com/"]] },
          { id: "s2", n: "Frontend & Dashboards", c: 3, h: 28, lv: 3, core: false,
            g: ["Build usable UI (you don't need to be a designer)", "Charts that persuade customers", "Forms, loading states, error handling"],
            cp: "Build a dashboard the customer actually opens every morning",
            r: [["MDN Learn Web Dev", "https://developer.mozilla.org/en-US/docs/Learn"]] },
          { id: "s3", n: "System Design Primer", c: 4, h: 30, lv: 4, core: true,
            g: ["Capacity estimates, caching, queues, rate limits", "Monolith vs split — how to decide", "Degradation when a dependency dies"],
            cp: "Diagram a real scenario and explain each component's failure cost",
            r: [["The Twelve-Factor App", "https://12factor.net/"]] },
          { id: "s4", n: "Testing & Quality", c: 3, h: 20, lv: 3, core: false,
            g: ["Unit / integration / e2e layering", "Fixtures and contract tests", "Add the net before touching old code"],
            cp: "Add critical-path tests to an untested legacy module",
            r: [["pytest Docs", "https://docs.pytest.org/"]] },
          { id: "s5", n: "CI/CD Pipelines", c: 3, h: 18, lv: 3, core: true,
            g: ["Build, test, image, release in one flow", "Environment tiers, canary, rollback", "Script every manual step away"],
            cp: "Build a pipeline: push → test → image → deploy → auto-rollback on failure",
            r: [["GitHub Actions Docs", "https://docs.github.com/actions"]] },
        ],
      },
      {
        id: "ai", icon: "🧠", name: "Data & AI", sub: "2026 core", color: "#ff8fb1",
        desc: "An FDE in 2026 who can't ship AI is like one in 2016 who couldn't write SQL. Focus on engineering, not alchemy.",
        courses: [
          { id: "a1", n: "Data Pipelines & ETL", c: 3, h: 26, lv: 3, core: true,
            g: ["Batch vs streaming", "Dirty data, reconciliation, backfills", "Extracting from Excel / SAP / APIs"],
            cp: "Turn three messy customer sources into one trusted table with a reconciliation report",
            r: [["Apache Airflow Docs", "https://airflow.apache.org/docs/"]] },
          { id: "a2", n: "RAG & Vector Search", c: 4, h: 30, lv: 4, core: true,
            g: ["Chunking, embeddings, recall, reranking", "Vector store selection, hybrid search", "Citations and hallucination control"],
            cp: "Ship a document assistant with a measured accuracy rate, not vibes",
            r: [["Qdrant Documentation", "https://qdrant.tech/documentation/"]] },
          { id: "a3", n: "LLM Application Engineering", c: 4, h: 30, lv: 3, core: true,
            g: ["Structured output, tool calls, retries", "Streaming UX, timeouts", "Model choice: quality / cost / compliance"],
            cp: "Launch an LLM feature with guardrails, logging and a fallback path",
            r: [["OpenAI Docs", "https://platform.openai.com/docs"], ["Anthropic Docs", "https://docs.anthropic.com/"]] },
          { id: "a4", n: "Agents & Tool Use", c: 4, h: 32, lv: 5, core: false,
            g: ["When NOT to use an agent", "Tool design, state, context compaction", "Human approval and audit trails"],
            cp: "Automate a workflow with a human-in-the-loop step and justify it over a script",
            r: [["12-Factor Agents (methodology)", null]] },
          { id: "a5", n: "Evals, Cost & Prompting", c: 3, h: 20, lv: 3, core: true,
            g: ["Start an eval set with 20 real samples", "Token / latency / caching cost math", "Prompt versioning and regression tests"],
            cp: "Build a repeatable eval for your AI feature and propose a cost cut",
            r: [["OpenAI Evals Guide", "https://platform.openai.com/docs/guides/evals"]] },
        ],
      },
      {
        id: "infra", icon: "🛠️", name: "Deployment & Infra", sub: "on-site", color: "#ffd166",
        desc: "\"It works on my machine\" does not exist on a customer site. This department trains cross-environment delivery.",
        courses: [
          { id: "i1", n: "Docker & Image Engineering", c: 3, h: 20, lv: 2, core: true,
            g: ["Layers, caching, slimming, scanning", "Multi-arch images (x86 / ARM)", "Reproducing production locally"],
            cp: "Containerize a legacy project with before/after size and startup numbers",
            r: [["Docker Get Started", "https://docs.docker.com/get-started/"]] },
          { id: "i2", n: "Kubernetes Fundamentals", c: 4, h: 32, lv: 4, core: true,
            g: ["Pods, Services, Ingress, ConfigMaps", "Limits, probes, rolling updates", "Debug with kubectl, not just apply"],
            cp: "Deploy a three-tier service and run a zero-downtime rollout",
            r: [["Kubernetes Tutorials", "https://kubernetes.io/docs/tutorials/"]] },
          { id: "i3", n: "Cloud & Infrastructure as Code", c: 4, h: 30, lv: 4, core: true,
            g: ["Terraform resource lifecycle", "Multi-cloud differences and lock-in risk", "Layered environments and secrets"],
            cp: "Provision an entire environment in code and reproduce it in another account",
            r: [["Terraform Docs", "https://developer.hashicorp.com/terraform/docs"]] },
          { id: "i4", n: "Observability (Logs, Metrics, Traces)", c: 3, h: 22, lv: 3, core: true,
            g: ["What each signal is for", "SLOs and alerts that don't page humans", "Proving a change actually helped"],
            cp: "Instrument a service and run one honest incident post-mortem",
            r: [["OpenTelemetry Docs", "https://opentelemetry.io/docs/"]] },
          { id: "i5", n: "Air-gapped, Edge & On-Prem Delivery", c: 4, h: 28, lv: 5, core: true,
            g: ["Intranet / no-internet / sovereign environments", "Offline bundles and mirrored dependencies", "Data-residency constraints"],
            cp: "Do a full deployment with no internet and write a repeatable delivery manual",
            r: [["Air-gapped Kubernetes (search term)", null]] },
        ],
      },
      {
        id: "fde", icon: "🎯", name: "Forward Deployed Skills", sub: "the moat", color: "#ff6b81",
        desc: "The reason this academy exists. Skills get you hired; these get you kept.",
        courses: [
          { id: "d1", n: "Discovery & Problem Framing", c: 4, h: 24, lv: 4, core: true,
            g: ["Turn \"we want AI\" into an acceptance-tested problem", "Shadow a real workflow for a day", "Separate real, fake and political requirements"],
            cp: "Ship a one-page problem statement the customer signs off on",
            r: [["The Mom Test (book)", null]] },
          { id: "d2", n: "Rapid Prototyping: 72h POC", c: 4, h: 30, lv: 4, core: true,
            g: ["Fake data first, experience first", "Cut scope to the 20% that wows", "Courage to write throwaway code"],
            cp: "Deliver a demoable prototype in 72 hours with an explicit \"out of scope\" list",
            r: [["POC-to-production gap (search term)", null]] },
          { id: "d3", n: "Demos & Storytelling", c: 3, h: 18, lv: 3, core: true,
            g: ["Speak the customer's language, not jargon", "One memorable point per demo", "Rehearse the failure path"],
            cp: "Give a 10-minute demo the customer can re-explain afterwards",
            r: [["Made to Stick (book)", null]] },
          { id: "d4", n: "Expectation & Stakeholder Management", c: 3, h: 20, lv: 4, core: true,
            g: ["Weekly notes, risk lists, bad news early", "Handle customer IT, business and security at once", "The art of saying no without losing the deal"],
            cp: "Eight weeks of weekly updates with zero surprise escalations",
            r: [["Crucial Conversations (book)", null]] },
          { id: "d5", n: "Delivery, Docs & Knowledge Transfer", c: 3, h: 20, lv: 3, core: true,
            g: ["Deliverable lists and acceptance docs", "Docs are only good if they get used", "Train the customer to run it alone"],
            cp: "Deliver docs, training video, runbook and handover; customer runs it for two weeks unaided",
            r: [["Write the Docs Guide", "https://www.writethedocs.org/guide/"]] },
          { id: "d6", n: "From POC to Product", c: 4, h: 28, lv: 5, core: true,
            g: ["Find the reusable parts", "Turn one project into a standard component", "Judge when something isn't worth repeating"],
            cp: "Abstract a past project into a reusable offering: second delivery 50% faster",
            r: [["Inspired (book)", null]] },
        ],
      },
      {
        id: "cap", icon: "🏆", name: "Capstone Projects", sub: "ship it", color: "#9d7cff",
        desc: "Before graduation you must actually deliver. Every project needs an artifact and a retrospective.",
        courses: [
          { id: "p1", n: "Project 1: Data Onboarding & Dashboard", c: 5, h: 40, lv: 3, core: true,
            g: ["Ingest and clean real messy data", "Build a dashboard they open daily", "Document metric definitions"],
            cp: "Dashboard + data dictionary + a data-trustworthiness note",
            r: [["Metabase Docs", "https://www.metabase.com/docs/latest/"]] },
          { id: "p2", n: "Project 2: Air-gapped Deployment Drill", c: 5, h: 45, lv: 5, core: true,
            g: ["Full deploy with no internet", "Offline dependency and image bundling", "Manual and rollback plan"],
            cp: "Deploy in a simulated offline network and write the repeatable manual",
            r: [["Kubernetes Docs", "https://kubernetes.io/docs/home/"]] },
          { id: "p3", n: "Project 3: Ship a RAG Assistant", c: 5, h: 45, lv: 4, core: true,
            g: ["Real corpus, real eval set", "Citations and human fallback", "Cost and latency tuning"],
            cp: "Launch the assistant with accuracy, cost and user-feedback numbers",
            r: [["Qdrant Documentation", "https://qdrant.tech/documentation/"]] },
          { id: "p4", n: "Project 4: Workflow Automation & Agents", c: 5, h: 45, lv: 5, core: false,
            g: ["Pick a high-frequency manual process", "Human confirmation and audit trail", "Measure hours saved"],
            cp: "Automate a process with measured hours saved and a risk list",
            r: [["Anthropic Tool Use Docs", "https://docs.anthropic.com/"]] },
          { id: "p5", n: "Capstone: Deliver a Full Customer Project", c: 6, h: 80, lv: 5, core: true,
            g: ["Discovery → launch → handover, end to end", "Retrospective: trade-offs and lessons", "Be able to tell the story in 15 minutes"],
            cp: "Full delivery + retrospective + a 15-minute story → apply to graduate",
            r: [["Palantir on Forward Deployed Engineering", "https://www.palantir.com/"]] },
        ],
      },
    ],

    semesters: [
      { no: "S1", title: "Foundations (months 1–3)", goal: "Fill the gaps; debug on a server without help.",
        items: ["Linux & CLI", "Git & collaboration", "Networking & APIs", "Python for production", "SQL & modeling"],
        out: "Artifact: a containerized, tested, CI-backed little tool" },
      { no: "S2", title: "Engineering (months 4–7)", goal: "Ship a service that runs, is observable and can roll back.",
        items: ["Backend services", "System design", "Docker & images", "CI/CD", "Observability"],
        out: "Artifact: a commit-to-production pipeline plus one live service" },
      { no: "S3", title: "Intelligence (months 8–12)", goal: "Wire AI into the business as engineering, not as a demo.",
        items: ["Data pipelines", "RAG & vector search", "LLM engineering", "Evals & cost", "Kubernetes"],
        out: "Artifact: an AI feature with measurable effect, evals and a cost sheet" },
      { no: "S4", title: "The Front Line (months 13–18)", goal: "Get on site and turn technology into business outcomes.",
        items: ["Discovery", "72h POC", "Demos", "Expectation management", "Handover", "Capstone"],
        out: "Artifact: one full customer delivery + retrospective + diploma" },
    ],

    rules: [
      { t: "Go on site before you code", d: "A day at the customer's desk beats ten pages of requirements. The real problem hides in habits they no longer notice." },
      { t: "A demo beats perfection", d: "Something clickable on Wednesday beats a perfect design at month-end. Earlier feedback, less rework." },
      { t: "Deliver bad news early", d: "Slips, risks, impossible features — early is professional, late is an incident." },
      { t: "Code must be handover-able", d: "You will leave this project eventually. READMEs, scripts and docs are the next person's life jacket." },
      { t: "Design for failure", d: "Dependencies die, networks drop, models hallucinate. Decide what users see when each piece breaks." },
      { t: "Cutting scope is a core skill", d: "Usually only 20% of features move the decision maker. Find it and cut the rest bravely." },
      { t: "It isn't done until it's delivered", d: "Running ≠ delivered. They use it, they want to, and they can without you." },
    ],
  },
};
